### PR TITLE
Updated member list

### PR DESCRIPTION
**Pull request by jeffreyjgong**
Closes issue #6

### CODE REVIEW

**Comment by jeffreyjgong** [comment]
@dannymota Where's the RDB hosted? Because the changes in this PR aren't reflected on the actual site.

**Comment by dannymota** [comment]
You’ll have to update the main branch on Heroku. Here’s a quick guide to do
so: https://devcenter.heroku.com/articles/git. Let me know if you need the
login

**Comment by jeffreyjgong** [comment]
@dannymota Yeah, I think I might need the Heroku App name and the login

**Comment by dannymota** [comment]
Sent it to your email address

**Comment by jeffreyjgong** [comment]
@dannymota Worked! Thanks

**Pull request merged**
